version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: test
    ports:
      - "5672:5672"
      - "15672:15672"

  producer:
    image: producer
    container_name: producer
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  consumer:
    image: consumer
    container_name: consumer
    build:
      context: ./consumer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq